<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Monthly Sales Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .report-title {
            font-size: 20px;
            margin-bottom: 20px;
        }
        .meta-data {
            font-size: 12px;
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
        }
        .section-header {
            font-weight: bold;
            margin: 15px 0;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">Kyla and Kyle Catering Services</div>
        <div class="report-title">Monthly Sales Report</div>
        <div class="meta-data">Generated by: {{ session('fname') }} {{ session('lname') }}</div>
        <div class="meta-data">Date Generated: {{ now()->format('F d, Y h:i:s A') }}</div>
        @if(isset($filters))
            @if($filters['year'])
                <div class="meta-data">Year: {{ $filters['year'] }}</div>
            @endif
            @if($filters['month'])
                <div class="meta-data">Month: {{ $months[$filters['month'] - 1] }}</div>
            @endif
        @endif
    </div>

    @foreach($yearlyData as $year => $data)
        @if(!isset($filters['year']) || $filters['year'] == $year)
            <div class="section-header">Monthly Summary ({{ $year }})</div>
            
            <!-- Monthly Details -->
            <table>
                <thead>
                    <tr>
                        <th>Month</th>
                        <th>Reservation Fees</th>
                        <th>Package Sales</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($months as $index => $month)
                        @if(!isset($filters['month']) || $filters['month'] == $index + 1)
                            <tr>
                                <td>{{ $month }}</td>
                                <td>₱{{ number_format($data['reservationFees'][$index], 2) }}</td>
                                <td>₱{{ number_format($data['totalPrices'][$index], 2) }}</td>
                                <td>₱{{ number_format($data['reservationFees'][$index] + $data['totalPrices'][$index], 2) }}</td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        @endif
    @endforeach
</body>
</html>