<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pending Projects List PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0; /* Add this line to remove default margin */
            padding-bottom: 40px; /* Add this line to create space for the footer */
        }

        .card {
            margin: auto;
            width: 90%;
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 6px;
        }

        h1 {
            font-size: 1.5em;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: #f1f1f1;
            padding: 10px 0;
            text-align: right;
            font-size: 0.8em;
        }

        .footer p {
            margin: 0 10px;
        }
        @media print {
            /* Add the same changes to the print media query */
            body {
                margin: 0;
                padding-bottom: 40px;
            }

            .footer {
                position: fixed;
                bottom: 0;
                left: 0;
                width: 100%;
                background-color: #f1f1f1;
                padding: 10px 0;
                text-align: right;
                font-size: 0.8em;
            }

            .footer p {
                margin: 0 10px;
            }
        }
    </style>
</head>
<body>
<div class="card">
        <h1>Kyla and Kyle Catering Services</h1>
        <h2>Sales Report</h2>

        <!-- Yearly Summary -->
        <div class="section-header">Yearly Summary ({{date('Y')}})</div>
        <table>
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Total Reservation Fees</td>
                    <td>₱{{ number_format($yearlyFees, 2) }}</td>
                </tr>
                <tr>
                    <td>Total Package Sales</td>
                    <td>₱{{ number_format($yearlyPrices, 2) }}</td>
                </tr>
                <tr>
                    <td><strong>Total Sales</strong></td>
                    <td><strong>₱{{ number_format($yearlyFees + $yearlyPrices, 2) }}</strong></td>
                </tr>
            </tbody>
        </table>

        <!-- Monthly Summary -->
        <div class="section-header">Monthly Summary</div>
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Reservation Fees</th>
                    <th>Package Sales</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($months as $index => $month)
                <tr>
                    <td>{{ $month }}</td>
                    <td>₱{{ number_format($reservationFees[$index], 2) }}</td>
                    <td>₱{{ number_format($totalPrices[$index], 2) }}</td>
                    <td>₱{{ number_format($reservationFees[$index] + $totalPrices[$index], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Weekly Summary -->
        <div class="section-header">Weekly Summary ({{ date('F') }})</div>
            <table>
                <thead>
                    <tr>
                        <th>Week</th>
                        <th>Reservation Fees</th>
                        <th>Package Sales</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @for($week = 0; $week < 4; $week++)
                    <tr>
                        <td>Week {{ $week + 1 }}</td>
                        <td>₱{{ number_format($weeklyFees[$week], 2) }}</td>
                        <td>₱{{ number_format($weeklyPrices[$week], 2) }}</td>
                        <td>₱{{ number_format($weeklyFees[$week] + $weeklyPrices[$week], 2) }}</td>
                    </tr>
                    @endfor
                </tbody>
            </table>
        </div>

    <div class="footer">
        <p>Generated by: {{session('fname')}}</p>
        <p>Date Generated: {{ now() }}</p>
    </div>

    <script>
        window.onload = function () {
            window.print();
        };
    </script>
</body>
</html>