<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Sales Report</title>
    <style>
        @page {
            margin: 0cm 0cm;
        }
        
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            padding: 20px;
            margin-bottom: 30px;
            font-size: 12px;
        }

        main {
            margin-bottom: 50px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .report-title {
            font-size: 20px;
            margin-bottom: 20px;
        }

        .meta-data {
            font-size: 12px;
            margin-bottom: 5px;
        }

        .card {
            margin: 20px auto;
            width: 100%;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            page-break-inside: auto;
        }

        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }

        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
            font-size: 12px;
        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }

        .section-header {
            font-weight: bold;
            margin: 15px 0;
            font-size: 16px;
            background-color: #f8f8f8;
            padding: 5px;
            border: 1px solid #ddd;
        }

        .monthly-section {
            margin-bottom: 20px;
        }

        .page-break {
            page-break-before: always;
        }

        #footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 30px;
            text-align: right;
            font-size: 10px;
            padding: 10px 20px;
            background-color: #fff;
            border-top: 1px solid #ddd;
        }

        .page-number:before {
            content: counter(page);
        }

        .page-total:before {
            content: counter(pages);
        }
    </style>
</head>
<body>
    <main>
        <div class="header">
            <div class="company-name">Kyla and Kyle Catering Services</div>
            <div class="report-title">Sales Report</div>
            <div class="meta-data">Generated by: {{ session('fname') }} {{ session('lname') }}</div>
            <div class="meta-data">Date Generated: {{ now()->format('F d, Y h:i:s A') }}</div>
            @if(isset($filters))
                @if($filters['report_type'])
                    <div class="meta-data">Report Type: {{ ucfirst($filters['report_type']) }}</div>
                @endif
                @if($filters['year'])
                    <div class="meta-data">Year: {{ $filters['year'] }}</div>
                @endif
                @if($filters['month'])
                    <div class="meta-data">Month: {{ $months[$filters['month'] - 1] }}</div>
                @endif
                @if($filters['week'])
                    <div class="meta-data">Week: {{ $filters['week'] }}</div>
                @endif
            @endif
        </div>

        <div class="card">
            @php
                $sortedYears = $yearlyData;
                krsort($sortedYears);
            @endphp

            @foreach($sortedYears as $year => $data)
                @if(!$loop->first)
                    <div class="page-break"></div>
                @endif

                <!-- Yearly Summary -->
                <div class="section-header">Yearly Summary ({{ $year }})</div>
                <table>
                    <thead>
                        <tr>
                            <th>Category</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Total Reservation Fees</td>
                            <td>PHP {{ number_format($data['yearlyFees'], 2) }}</td>
                        </tr>
                        <tr>
                            <td>Total Package Sales</td>
                            <td>PHP {{ number_format($data['yearlyPrices'], 2) }}</td>
                        </tr>
                        <tr>
                            <td><strong>Total Sales</strong></td>
                            <td><strong>PHP {{ number_format($data['yearlyFees'] + $data['yearlyPrices'], 2) }}</strong></td>
                        </tr>
                    </tbody>
                </table>

                <!-- Monthly Summary -->
                <div class="section-header">Monthly Summary</div>
                <table>
                    <thead>
                        <tr>
                            <th>Month</th>
                            <th>Reservation Fees</th>
                            <th>Package Sales</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($months as $index => $month)
                        <tr>
                            <td>{{ $month }}</td>
                            <td>PHP {{ number_format($data['reservationFees'][$index], 2) }}</td>
                            <td>PHP {{ number_format($data['totalPrices'][$index], 2) }}</td>
                            <td>PHP {{ number_format($data['reservationFees'][$index] + $data['totalPrices'][$index], 2) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

                <!-- Weekly Summary for Each Month -->
                @foreach($months as $index => $month)
                <div class="section-header">Weekly Summary - {{ $month }}</div>
                <table>
                    <thead>
                        <tr>
                            <th>Week</th>
                            <th>Reservation Fees</th>
                            <th>Package Sales</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for($week = 0; $week < 4; $week++)
                        <tr>
                            <td>Week {{ $week + 1 }}</td>
                            <td>PHP {{ number_format($data['weeklyData'][$index + 1]['weeklyFees'][$week] ?? 0, 2) }}</td>
                            <td>PHP {{ number_format($data['weeklyData'][$index + 1]['weeklyPrices'][$week] ?? 0, 2) }}</td>
                            <td>PHP {{ number_format(($data['weeklyData'][$index + 1]['weeklyFees'][$week] ?? 0) + ($data['weeklyData'][$index + 1]['weeklyPrices'][$week] ?? 0), 2) }}</td>
                        </tr>
                        @endfor
                    </tbody>
                </table>
                @endforeach
            @endforeach
        </div>
    </main>
</body>
</html>