<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pending Projects List PDF</title>
    <link rel="icon" href="data:;base64,="> <!-- Disable Laravel favicon -->
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0;
            padding-bottom: 40px;
        }

        .card {
            margin: auto;
            width: 90%;
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 6px;
        }

        h1, h2 {
            font-size: 1.5em;
        }

        .section-header {
            font-weight: bold;
            margin: 10px 0;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: #f1f1f1;
            padding: 10px 0;
            text-align: right;
            font-size: 0.8em;
        }

        .footer p {
            margin: 0 10px;
        }

        .page-break {
            page-break-before: always;
        }

        @media print {
            body {
                margin: 0;
                padding-bottom: 40px;
            }

            .footer {
                position: fixed;
                bottom: 0;
                left: 0;
                width: 100%;
                background-color: #f1f1f1;
                padding: 10px 0;
                text-align: right;
                font-size: 0.8em;
            }

            .footer p {
                margin: 0 10px;
            }

            .page-break {
                page-break-before: always;
            }
        }
    </style>
</head>
<body>
<div class="card">
    <h1>Kyla and Kyle Catering Services</h1>
    <h2>Sales Report</h2>

    @php
        $sortedYears = $yearlyData;
        krsort($sortedYears);
    @endphp

    @foreach($sortedYears as $year => $data)
    <div class="{{ $loop->first ? '' : 'page-break' }}">
        <!-- Rest of your existing code remains the same -->
        <div class="section-header">Yearly Summary ({{ $year }})</div>
        <table>
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Total Reservation Fees</td>
                    <td>₱{{ number_format($data['yearlyFees'], 2) }}</td>
                </tr>
                <tr>
                    <td>Total Package Sales</td>
                    <td>₱{{ number_format($data['yearlyPrices'], 2) }}</td>
                </tr>
                <tr>
                    <td><strong>Total Sales</strong></td>
                    <td><strong>₱{{ number_format($data['yearlyFees'] + $data['yearlyPrices'], 2) }}</strong></td>
                </tr>
            </tbody>
        </table>

        <!-- Monthly Summary -->
        <div class="section-header">Monthly Summary</div>
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Reservation Fees</th>
                    <th>Package Sales</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($months as $index => $month)
                <tr>
                    <td>{{ $month }}</td>
                    <td>₱{{ number_format($data['reservationFees'][$index], 2) }}</td>
                    <td>₱{{ number_format($data['totalPrices'][$index], 2) }}</td>
                    <td>₱{{ number_format($data['reservationFees'][$index] + $data['totalPrices'][$index], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Weekly Summary -->
        <div class="section-header">Weekly Summary ({{ date('F') }})</div>
        <table>
            <thead>
                <tr>
                    <th>Week</th>
                    <th>Reservation Fees</th>
                    <th>Package Sales</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['weeklyFees'] as $week => $fee)
                <tr>
                    <td>Week {{ $week + 1 }}</td>
                    <td>₱{{ number_format($fee, 2) }}</td>
                    <td>₱{{ number_format($data['weeklyPrices'][$week], 2) }}</td>
                    <td>₱{{ number_format($fee + $data['weeklyPrices'][$week], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endforeach
</div>

<div class="footer">
    <p>Generated by: {{session('fname')}}</p>
    <p>Date Generated: {{ now() }}</p>
</div>

<script>
    window.onload = function () {
        window.print();
    };
</script>
</body>
</html>
