<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Weekly Sales Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .report-title {
            font-size: 20px;
            margin-bottom: 20px;
        }
        .meta-data {
            font-size: 12px;
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
        }
        .section-header {
            font-weight: bold;
            margin: 15px 0;
            font-size: 16px;
        }
        .monthly-section {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">Kyla and Kyle Catering Services</div>
        <div class="report-title">Weekly Sales Report</div>
        <div class="meta-data">Generated by: {{ session('fname') }} {{ session('lname') }}</div>
        <div class="meta-data">Date Generated: {{ now()->format('F d, Y h:i:s A') }}</div>
        @if(isset($filters))
            @if($filters['year'])
                <div class="meta-data">Year: {{ $filters['year'] }}</div>
            @endif
            @if($filters['month'])
                <div class="meta-data">Month: {{ $months[$filters['month'] - 1] }}</div>
            @endif
            @if($filters['week'])
                <div class="meta-data">Week: {{ $filters['week'] }}</div>
            @endif
        @endif
    </div>
    @foreach($yearlyData as $year => $data)
        @if(!isset($filters['year']) || $filters['year'] == $year)
            @foreach($months as $index => $month)
                @if(!isset($filters['month']) || $filters['month'] == $index + 1)
                    <div class="monthly-section">
                        <div class="section-header">{{ $month }} {{ $year }}</div>
                        <table>
                            <thead>
                                <tr>
                                    <th>Week</th>
                                    <th>Reservation Fees</th>
                                    <th>Package Sales</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for($week = 0; $week < 4; $week++)
                                    @if(!isset($filters['week']) || $filters['week'] == $week + 1)
                                        <tr>
                                            <td>Week {{ $week + 1 }}</td>
                                            <td>₱{{ number_format($data['weeklyData'][$index + 1]['weeklyFees'][$week] ?? 0, 2) }}</td>
                                            <td>₱{{ number_format($data['weeklyData'][$index + 1]['weeklyPrices'][$week] ?? 0, 2) }}</td>
                                            <td>₱{{ number_format(
                                                ($data['weeklyData'][$index + 1]['weeklyFees'][$week] ?? 0) + 
                                                ($data['weeklyData'][$index + 1]['weeklyPrices'][$week] ?? 0), 
                                                2) 
                                            }}</td>
                                        </tr>
                                    @endif
                                @endfor
                            </tbody>
                        </table>
                    </div>
                @endif
            @endforeach
        @endif
    @endforeach
</body>
</html>