<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservation Report PDF</title>
    <link rel="icon" href="data:;base64,="> <!-- Disable Laravel favicon -->
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0;
            padding-bottom: 60px; /* Adjust to match footer height */
        }

        .card {
            margin: auto;
            width: 90%;
            margin-top: 20px;
            padding-bottom: 60px; /* Match footer height */
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 6px;
        }

        h1, h2 {
            font-size: 1.5em;
        }

        .section-header {
            font-weight: bold;
            margin: 10px 0;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: rgba(241, 241, 241, 0.8); /* Semi-transparent light gray */
            padding: 10px 0;
            text-align: right;
            font-size: 0.8em;
            height: 40px; /* Fixed height for consistency */
        }

        .section-header {
            font-weight: bold;
            margin: 10px 0;
        }

        .header {
            text-align: center;
            font-size: 0.8em;
            margin-bottom: 20px;
        }

        .header p {
            margin: 0;
        }

        .footer p {
            margin: 0 10px;
        }

        .page-break {
            page-break-before: always;
        }

        @media print {
            body {
                margin: 0;
                padding-bottom: 60px; /* Match footer height */
            }

            .footer {
                position: fixed;
                bottom: 0;
                left: 0;
                width: 100%;
                background-color: rgba(241, 241, 241, 0.8);
                padding: 10px 0;
                text-align: right;
                font-size: 0.8em;
            }

            .footer p {
                margin: 0 10px;
            }

            .page-break {
                page-break-before: always;
            }
        }
    </style>
</head>
<body>

<div class="header">
    <p>Generated by: {{ session('fname') }}</p>
    <p>Date Generated: {{ now() }}</p>
</div>

<div class="card">
    <h1>Kyla and Kyle Catering Services</h1>
    <h2>Reservation Report</h2>

    @php
        $sortedYears = $yearlyReservations;
        krsort($sortedYears);
    @endphp

    @foreach($sortedYears as $year => $count)
    <div class="{{ $loop->first ? '' : 'page-break' }}">
        <!-- Yearly Summary -->
        <div class="section-header">Yearly Summary ({{ $year }})</div>
        <table>
            <thead>
                <tr>
                    <th>Year</th>
                    <th>Total Reservations</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $year }}</td>
                    <td>{{ $count }}</td>
                </tr>
            </tbody>
        </table>

        <!-- Monthly Summary -->
        <div class="section-header">Monthly Summary</div>
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Reservations</th>
                </tr>
            </thead>
            <tbody>
                @foreach($months as $index => $month)
                <tr>
                    <td>{{ $month }}</td>
                    <td>{{ $monthlyReservations[$index] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Weekly Summary -->
        <div class="section-header">Weekly Summary</div>
        @foreach($months as $index => $month)
        <div class="monthly-section">
            <div class="section-header">{{ $month }}</div>
            <table>
                <thead>
                    <tr>
                        <th>Week</th>
                        <th>Reservations</th>
                    </tr>
                </thead>
                <tbody>
                    @for($week = 0; $week < 4; $week++)
                    <tr>
                        <td>Week {{ $week + 1 }}</td>
                        <td>{{ $weeklyReservationsByMonth[$index + 1][$week] }}</td>
                    </tr>
                    @endfor
                </tbody>
            </table>
        </div>
        @endforeach
    </div>
    @endforeach
</div>

<script>
    window.onload = function () {
        window.print();
    };
</script>
</body>
</html>
