<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Yearly Reservation Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .report-title {
            font-size: 20px;
            margin-bottom: 20px;
        }
        .meta-data {
            font-size: 12px;
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
        }
        .section-header {
            font-weight: bold;
            margin: 15px 0;
            font-size: 16px;
        }
        .page-break {
            page-break-before: always;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">Kyla and Kyle Catering Services</div>
        <div class="report-title">Yearly Reservation Report</div>
        <div class="meta-data">Generated by: {{ session('fname') }} {{ session('lname') }}</div>
        <div class="meta-data">Date Generated: {{ now()->format('F d, Y h:i:s A') }}</div>
        @if(isset($filters['year']))
            <div class="meta-data">Year: {{ $filters['year'] }}</div>
        @endif
    </div>

    @php
        $sortedYears = $yearlyData;
        krsort($sortedYears);
    @endphp

    @foreach($sortedYears as $year => $count)
        @if(!isset($filters['year']) || $filters['year'] == $year)
            
            <div class="section-header">Yearly Summary ({{ $year }})</div>
            <table>
                <thead>
                    <tr>
                        <th>Month</th>
                        <th>Reservations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($months as $index => $month)
                        <tr>
                            <td>{{ $month }}</td>
                            <td>{{ $monthlyTrends[$year][$index] }}</td>
                        </tr>
                    @endforeach
                    <tr>
                        <td><strong>Total</strong></td>
                        <td><strong>{{ array_sum($monthlyTrends[$year]) }}</strong></td>
                    </tr>
                </tbody>
            </table>
        @endif
    @endforeach
</body>
</html>